[package]
authors = ["Vanius Roberto Bittencourt <vanius@gmail.com>"]
edition = "2018"
name = "cpf_val"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"
